In [7]:
import pandas as pd

In [11]:
data = pd.read_csv("/Users/laven/Documents/TKH/shopping-behavior/data/processed/shopping_cleaned.csv")

In [12]:
data.head()

,Age,Gender,Item Purchased,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Shipping Type,Promo Code Used,Previous Purchases,Payment Method
0,31.0,Male,Leggings,24.231704,Nevada,M,Terra cotta,Winter,Present,Standard,No,0,Credit Card
1,38.0,Male,Sunglasses,36.545487,Oregon,S,Aubergine,Summer,Missing,Standard,No,0,Credit Card
2,26.0,Male,Leggings,23.595139,Nevada,XL,Brown,Winter,Missing,Standard,No,3,Credit Card
3,43.0,Male,Dress,34.079015,California,M,Terra cotta,Fall,Present,Standard,No,0,Credit Card
4,29.0,Male,Shorts,23.796439,Minnesota,M,Lavender,Summer,Present,Express,No,0,Credit Card

In [13]:
data.describe()

               Age  Purchase Amount (USD)  Previous Purchases
count  3158.000000            3158.000000         3158.000000
mean     34.185244              38.812750            5.860988
std      10.578195              11.525595            5.844408
min      18.000000              11.946095            0.000000
25%      26.000000              29.419108            1.000000
50%      33.000000              37.126663            4.000000
75%      41.000000              48.974363            9.000000
max      73.000000              68.327455           20.000000

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3158 entries, 0 to 3157
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    3158 non-null   float64
 1   Gender                 3158 non-null   str
 2   Item Purchased         3158 non-null   str
 3   Purchase Amount (USD)  3158 non-null   float64
 4   Location               3158 non-null   str
 5   Size                   3158 non-null   str
 6   Color                  3158 non-null   str
 7   Season                 3158 non-null   str
 8   Review Rating          3158 non-null   str
 9   Shipping Type          3158 non-null   str
 10  Promo Code Used        3158 non-null   str
 11  Previous Purchases     3158 non-null   int64
 12  Payment Method         3158 non-null   str
dtypes: float64(2), int64(1), str(10)
memory usage: 320.9 KB

Step 1: Data Exploration
Each row represents a single customer, male or female who made a unique purchase at a given state in the US. The Numeric columns are: Purchase Amount and Previous Purchases.The Categorical columns are: Age, Gender, Item Purchased, Location, Size, Color, Season, Review Rating, Shipping Type, Promo Code Use, and Payment Method. A FlashFash executive would care most about sales volume.

Step 2: